## Домашнее задание «Библиотека numpy. Вычислительные задачи»
Преподаватель: Константин Башевой
Домашнее задание

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

# Задание 1 
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [11]:
import numpy as np 

In [12]:
a = np.arange(-9,1)*(-1)
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
b = np.flip(np.arange(0,10))
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2 
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [18]:
N = 10
matrix_1 = np.diag(np.flip(np.arange(0,N+1)), k=0)
matrix_1

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [19]:
# сумма элементов по диагонали
np.trace(matrix_1)

55

# Задание 3 
Решите систему уравнений: 
4x + 2y + z = 4   
x + 3y = 12   
5y + 4z = -3    

In [22]:
a = np.array( [ [4,2,1], [1,3,0],[0,5,4] ] )
b = np.array( [4,12,-3] )
from numpy import linalg
solution = linalg.solve(a, b)
print(f'x={solution[0]}, y={solution[1]}, z={solution[2]}')

x=0.4666666666666668, y=3.844444444444444, z=-5.555555555555555


# Задача 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

Матрица в виде numpy array

In [5]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [6]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [7]:
import matplotlib.pyplot as plt

In [8]:
def cosine(b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    a = next_user_stats
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [23]:
def select_similar_user():
    users_results = []
    for user in users_stats: 
        users_results.append(cosine(user))
        similar_user_ID = users_results.index(np.amax(users_results))+1
    print(f'Самый похожий: User ID = {similar_user_ID}')

In [24]:
select_similar_user()

Самый похожий: User ID = 8
